### ISSUE TITLE
outstanding issues for initial beta release

### ISSUE THREAD

**Issue by eplebel** [ScienceCommons/curate_science#46]
**Article List/Author Page**
- [x] update website-wide icon (new snail logo as on alpha page; [link to icon](http://curatescience.org/logos/author-logos/CS-snail-icon.png) )
- [x] add missing article type label borders for “reanalysis – reprod/robustness”, “reanalysis – meta-analysis”, and “reanalysis – meta-research” article types
- [x] move article type labels between journal name and transparency badges (see screenshot below; which requires updating article TITLE style to "margin-top: 0px; padding-top: 2px;" and transparency div style to "margin-bottom: 5px;")
![AT-below-journal-name](https://user-images.githubusercontent.com/4512335/55616823-fe039480-5792-11e9-848f-5914b9d8df57.png)
- [x] make publication year bold (incl. parentheses: i.e., "**(2019)**"; as in screenshot above).
- [ ] impact icons stylistic tweaks (view icon: "font-size: 14px; margin-bottom: -2px"; download: "font-size: 13px; margin-bottom: -1px"; citation: "font-size: 19px; margin-bottom: -5px")
- [x] replication details popup: for replication definition text: add margin-top: 15px, use correct grey color (#808080), and fix incorrect line break between ‘is’ and ‘close’ 
- [x] use correct [prereg+ badge](http://curatescience.org/logos/author-logos/sprite-icons/preregistered-plus-available.png) (we won't use badge w/out + given that we have prereg type text describing the preregistration type (i.e., whether study+ analyses vs. study only was preregistered))
- [x] add prereg type text in prereg popup based on preregistration type (“Preregistered study design + analyses”,  “Preregistered study design” , and “Peer-reviewed preregistered study design + analyses” for preg+, prereg, and Registered Report preregistration types, respectively); also increase size of content provider icon to match size of external link icon (see screenshot below):
![prereg-type-text](https://user-images.githubusercontent.com/4512335/55616224-9f89e680-5791-11e9-8a27-ce1df985a346.png)
- [x] add missing Registered Report label (which appears to the right of article type label; see first screenshot above), based on prereg type radio button value
- [x] add titles for non-popup article type labels (i.e., all labels except replication article type label):
  - Conceptual: "Article involves a conceptual/theoretical contribution"
  - Reanalysis  - Reproducibility/Robustness: "Article reports a reproducibility/robustness reanalysis of a previously published result"
  - Reanalysis - Metaanalysis: "Article reports a (traditional) meta-analysis of a target effect/phenomenon"
  - Reanalysis - Meta-research: "Article reports a reanalysis of results from previously published studies (meta-research)"
  - Commentary: "Article is a commentary on previous research"
  - Original: "Article reports original empirical observations (not directly comparable to previous research"
- [x] update Article selector placeholder text (to “Search articles by title or author last name”)
- [ ] fix transparency badge popup issues (issue #35)
- [ ] horizontally center the navbar so that its width is not 100% (which looks bad on large displays (as [explained here](https://github.com/ScienceCommons/curate_science/issues/36#issuecomment-476523117))
- [x] move action buttons outside of article card (to the right, as [explained here](https://github.com/ScienceCommons/curate_science/issues/37#issuecomment-476525354))
- [x] add missing link icon (so users can share/link to a specific article card; as on alpha page, [e.g.](http://curatescience.org/author/julia.rohrer.html#10.1177/0956797617723726))

**Article EDITOR**
- [x] display only article type-relevant badge input boxes (matching what's already implemented for displaying different badges for different article types):
  - Reanalysis  - Reproducibility/Robustness: hide "Public Study Materials URL" and "Reporting Standards" input boxes
  - Reanalysis - Metaanalysis & Reanalysis - Meta-research: hide "public Study Materials URL" input box
- [x] update text "Protocol Type" to "Preregistration Type"
- [x] fix impact metrics “as of Date” (it should be date of last edit for specific impact metric field; currently, it seems to be the date of last article edit (*OR* seems to be the correct date if 2 impact metric fields are updated)
- [x] within "ADD A FIGURE..." component, remove “ADD FIGURE” and “Cancel” buttons given that images automatically upload upon selection
- [x] fix issue whereby one can’t remove impact metric if full-text link has been entered (it says must enter integer, but if enter 0, one can proceed; steps: 1. enter full-text URL (for PDF, HTML, or Preprint), 2. enter an impact value (for any field) and save, 3. now go back and remove impact metric and save. Notice the error message.)
- [x] prevent invalid URLs from being inputted in edit author modal (issue #27)
- [ ] multiple file key figure upload 

**Other:**
- [x] focus cursor in first text box in various modals/components: i.e., on"New/Edit Article" modal (focus cursor in article title text box), "Edit Author" modal (focus cursor in Name field), and in text box of Article selector component (for "New/Edit Article" and "Edit Author" modals, if text box is non-empty, select the text)
- [x] reduce height of navbar to 56px (by decreasing min-height: 64px to 56px;)
- [x] raise error if admin tries to invite a user with pre-activated author page that is already linked to another user account (see [github comment](https://github.com/ScienceCommons/curate_science/issues/33#issuecomment-479343563))
- [x] update content/fix styles of About, FAQ, and People sections & footer (including Privacy and Terms of Service);  new and updated content as follows:
  - Updated "About" section: take from http://curatescience.org/#about (remember to update background-color of the About section to White instead of gray).
  - Updated "People" section: take from http://curatescience.org/#people (and it's fine to include "People" within the About section, as you've already done.)
  - Updated "FAQ" section: take from http://curatescience.org/#FAQ (again remember to update background-color to white instead of gray
  - Add "Newsletter" section: take from http://curatescience.org/#newsletter and please add link to "Newsletter" in the left-opening side drawer (so links will be "Replications", "About", "FAQ", "Newsletter", and "Help")
  - Update footer to what is on alpha homepage (just below http://curatescience.org/#newsletter)
  - For "Terms of Service" and "Privacy Policy", link to [Privacy page you already have](https://curatescience-staging.appspot.com/app/privacy), and display the following (temporary) text under two subsections:
     - Terms of Service: "As a condition of use of this website, you promise (1) to be honest, (2) to curate scientific information as accurately and impartially as possible, and (3) to not be a jerk. 
     - Privacy Policy: "We will never share or sell your personal information with anyone. Ever."

**Comment by alexkyllo** [comment]
>  raise error if admin tries to invite a user with pre-activated author page that is already linked to another user account (see github comment)

Just pushed this to staging.

**Comment by eplebel** [comment]
great, thanks Alex!

**Comment by onejgordon** [comment]
> update website-wide icon (new snail logo as on alpha page; link to icon )

Site-wide meaning the favicon? I replaced the top bar snail icon with a new vector version that I created based on the sample given which was a PNG and not ideal for multi-scale use. We can use this (either black or white, up to you) for the favicon as well.

> fix impact metrics “as of Date” (it should be date of last edit for specific impact metric field; currently, it seems to be the date of last article edit (OR seems to be the correct date if 2 impact metric fields are updated)

As far as I'm aware articles store a single update date, and do not have a property for each impact metric. @alexkyllo can confirm.

**Comment by onejgordon** [comment]
> within "ADD A FIGURE..." component, remove “ADD FIGURE” and “Cancel” buttons given that images automatically upload upon selection

Can we leave the 'cancel' button since otherwise there's no way to close the 'add a figure' panel that appears if user decides against it.

**Comment by eplebel** [comment]
> Can we leave the 'cancel' button since otherwise there's no way to close the 'add a figure' panel that appears if user decides against it.

sure

> Is this about the color of the article type label border?

yup looks fine

> Site-wide meaning the favicon?

yup that's what i meant, and please just use the existing one from the alpha site: http://curatescience.org/logos/author-logos/CS-snail-icon.png <link rel="icon" type="image/png" href="../logos/author-logos/CS-snail-icon.png">

> As far as I'm aware articles store a single update date, and do not have a property for each impact metric. 

ah ok, but i guess there's still a bug where if you edit a impact metric value, it doesn't display the correct update date. but if you change the same impact metric a 2nd time *or* a different impact metric value, it *does* display the correct update date (for example, i just updated # of downloads for "Heightened sensitivity.." article on https://curatescience-staging.appspot.com/app/author/etienne-lebel and it still says as of "3/31/2019"; but if i edit it a 2nd time, it will show the correct date). 

for the preregistration type text for Registered Report, please use the text "Peer-reviewed preregistered study design + analyses"

**Comment by onejgordon** [comment]
On update date, I'll look into why the UI isn't updating on each change, but to confirm: it's OK for now that *any* change to the article data model (e.g. title, authors, type, etc) will update the `updated` property, which is what shows when you hover over the impact measures.

**Comment by eplebel** [comment]
ya that's fine for now

**Comment by onejgordon** [comment]
> add missing link icon (so users can share/link to a specific article card; as on alpha page, e.g.)

@eplebel where do you want the link icon now that the article type badge has moved down?

**Comment by onejgordon** [comment]
> impact icons stylistic tweaks (view icon: "font-size: 14px; margin-bottom: -2px"; download: "font-size: 13px; margin-bottom: -1px"; citation: "font-size: 19px; margin-bottom: -5px")

I think what you're aiming to do here is vertically align the icons, and match up their size (since different icons take up slightly different amounts of the full character rectangle). I've adjusted the verticalAlign property of the icons to help do this in a slightly more robust way. I can still make the size tweaks if needed.

**Comment by eplebel** [comment]
> I think what you're aiming to do here is vertically align the icons, and match up their size (since different icons take up slightly different amounts of the full character rectangle). I've adjusted the verticalAlign property of the icons to help do this in a slightly more robust way. I can still make the size tweaks if needed.

yes after tweaking their size, they weren't vertically aligning correctly with the verticalAlign property, so i had to resort to the margin-bottom hack.

**Comment by eplebel** [comment]
> where do you want the link icon now that the article type badge has moved down?

good question. there's no obvious great spot for this now. ok let's just make it appear outside of  the card (top-left) as follows (eventually we'll also have social media sharing functionalities):
![article-card-share-links](https://user-images.githubusercontent.com/4512335/55865744-4948e900-5b7f-11e9-8ff8-2bb84999c9c4.png)

**Comment by onejgordon** [comment]
Linking should now be working on staging

**Comment by eplebel** [comment]
great, thanks so much!
i've tested it so please push to master branch, thanks.
