### ISSUE TITLE
outstanding known issues (mostly minor)

### ISSUE THREAD

**Issue by eplebel** [ScienceCommons/curate_science#50]
**most minor issues** (in rough order of difficulty/time to complete)
- [x] remove transparency badge line entirely when no badges present ([e.g.](https://curatescience.org/app/author/etienne-p-lebel#10.1177/2515245918787489); also decrease card margin-bottom from 24px to 16px, so they are all 16px (not sure how it got this way))
![Untitled-1](https://user-images.githubusercontent.com/4512335/56668697-45a18000-66b0-11e9-8034-00303b72dd67.png)
- [x] fix broken links to "replication taxonomy" PNG link within replication popup on homepage (from "https://curatescience.org/logos/replication-taxonomy-v4_small.png" to "https://curatescience.org/sitestatic/legacy/logos/replication-taxonomy-v4_small.png")
![Untitled-3](https://user-images.githubusercontent.com/4512335/56669006-c3fe2200-66b0-11e9-8c2d-1836694eca03.png)
- [x] add "Google Scholar" in citation title (i.e., "Article has been cited 20 times (as of December 15, 2018; Google Scholar)")
- [x] add Richard Shiffrin to advisory board on [about page](https://curatescience.org/app/about) (to the right of Mark Brandt; [headshot image](https://github.com/ScienceCommons/science-commons/blob/062317374beee2006a963c051792c8e9f89ac36d/logos/shiffrin_o.png), link headshot image to http://shiffrin.cogs.indiana.edu/, Richard Shiffrin, _Indiana University_(italicized).
    - [x] also update Wolf Vanpaemel's role from "Conceptual/Funding Advisor" to "Conceptual Advisor" and add Mike Morrison's missing affiliation (_"Michigan State University"_(italicized))
- [x] for DOI input text box, trim/remove the prefix "https://dx.doi.org/" if entered by the user (e.g., "https://dx.doi.org/10.1016/j.jesp.2013.10.005" should be trimmed to "10.1016/j.jesp.2013.10.005" (because we add the prefix automatically in the UI))
- [x] improved order of impact metrics: citations, downloads, and views *rather* than views, downloads, & citations (this means specifically: for PDFs (citations, downloads, & views) and preprints (downloads & views) 
- [x] 2 typos in AT drop-down: Re[a]nalysis – Meta-Analysis and Re[a]nalysis Meta-Research (missing 'a's)
- [x] for “reanalysis – meta-research” article type, hide reporting standard badge (in article list & edit article modal (because it's not applicable))
- [x] add supported image file types within add article component (i.e., .jpg, .gif, and .png)
- [x] add info icon w/ popup on hover (to the right of "ADD PREEXISTING ARTICLE" button) explaining the logic of linking pre-existing articles to one's author page: "Link an article to your author page that is already in our database (for example, an article that has already been added by one of your co-authors)." Also update text and icon within button as in mockup below (from "ADD PREEXISTING ARTICLE" to "LINK EXISTING ARTICLE"; link icon instead of add icon). (beta user feedback)
![link-existing-article-info-mockup](https://user-images.githubusercontent.com/4512335/56669760-ee9caa80-66b1-11e9-9c5f-b2f13bc74456.png)
- [x] horizontally center the navbar so that its width is not 100% (which looks bad on large displays (as explained [here](https://github.com/ScienceCommons/curate_science/issues/36#issuecomment-476523117))
- [x] integer input box controls (i.e., down-arrow) shouldn’t allow negative values
- [x] implement CTRL+  S keyboard shortcut within New/Edit article editor modal to SAVE changes!
- [x] fix transparency badge popup issues (issue #35; i.e., incorrectly auto-closes after about 1 sec. & hovering over a neighbor badge doesn't activate its popup)

**slightly more involved issues**
- [ ] improve article selector so one can see the entire title (by trimming authors text beyond 25 characters & by widening the autoCompleteReactSelect component itself from 428px to 700px )
- [ ] yield error message if non-supported file type is uploaded (i.e., “Image file type not supported. Only .jpg, .gif, and .png image file types are currently supported.”)
- [ ] remove delete figure tooltip for non-admin users (given that they don’t have permission to complete this action) 
- [ ] within Article selector component, HOME & END keys don’t work (useful when one wants to try a diff. key word)
- [ ] check duplicate article after leaving Title and DOI input boxes (rather than on Save; & display small button so they can link it to their author page)
- [ ] UNLINKING articles: add snack bar message confirming the unlinking with clickable “UNDO” (to undo the action)
- [ ] DELETING articles (ADMIN ONLY): add snack bar message confirming the deletion with clickable “UNDO” (to undo the action)
- [ ] secondary transparency previews (so user knows whether worth expanding; beta user feedback)
![secondary-transp-previews](https://user-images.githubusercontent.com/4512335/56275070-49f1fa00-6100-11e9-8cc2-9335c41176d6.png)
- [ ] mobile friendly (at least improve it so that it’s closer to specs, i.e., closer to mobile-friendliness of my [alpha author page](https://etiennelebel.com/))

**signup/login pages issues**
- [ ] convert to React pages
- [ ] after successful password reset, redirect to home page
- [ ] remove "Are you sure you want to sign out" warning page
- [ ] when user logs out in different tab (or browser cache is cleared), actions requiring being logged in don't work (expected behavior: should automatically bring user to log-in screen).

**admin-related issues**
- [ ] surface error if admin tries to invite user w/ pre-activated author page already linked to another user (see [github comment](https://github.com/ScienceCommons/curate_science/issues/33#issuecomment-479343563))
- [ ] improved admin dashboard (user list & basic details; new author & invite buttons; see paper mockup)
![admin-dashboard](https://user-images.githubusercontent.com/4512335/57515609-53dbd700-7313-11e9-8107-971ae8b1aa3e.png)

**Comment by alexkyllo** [comment]
>if user logs out in different tab (or browser cache is cleared), it doesn't automatically go to log-in screen if action requires being logged-in.

If you're saying what I think you're saying, I don't believe web browsers can do this--authentication uses session cookies, which are browser-wide, not tab-specific. If you want to be simultaneously logged-in and not logged-in in different tabs, I think the only way is to open another window in private/incognito mode, or a different browser.

**Comment by eplebel** [comment]
> If you want to be simultaneously logged-in and logged-out in different tabs, 

no this is not what i meant. i mean if a user logs out in a different tab (or clears cache) and then returns to original tab (where they appear still logged-in when in fact they're not) and then clicks EDIT ARTICLE, the action doesn't work and nothing happens. what should happen is that the user is redirected to the log-in page (so that they can return and complete the desired action). makes sense?
(but this is super low priority, so no need to think about it further for now)

**Comment by onejgordon** [comment]
> also decrease card margin-bottom from 24px to 16px, so they are all 16px (not sure how it got this way)

@eplebel which element are we decreasing margin bottom for? Can't quite tell from the screenshots what's being adjusted.

**Comment by onejgordon** [comment]
> for DOI input text box, trim/remove the prefix "https://dx.doi.org/" if entered by the user

For this, @alexkyllo do you think it's cleaner to do this on the server side (via some postgres pre-db-put validation operation), or should we validate prior to PATCH on client side?

**Comment by eplebel** [comment]
google scholar mentioned only for citations

**Comment by alexkyllo** [comment]
@onejgordon I think it's better to do that on the server side--strip off that URL prefix if it exists, before saving the article to the database. Probably using [django.db.models.signals.pre_save](https://docs.djangoproject.com/en/2.2/ref/signals/#django.db.models.signals.pre_save).

**Comment by onejgordon** [comment]
@alexkyllo I've implemented this in models in https://github.com/ScienceCommons/curate_science/commit/42030844bed7bcfa077fc2269d06eea6b7767a8e. Could you confirm this is a decent implementation? One issue that's still unresolved is I need to update the serialized object post validation (e.g. with stripped DOI url prefix) so that the UI updates with the real value. Currently it returns the full URL despite db being updated with properly validated url.

**Comment by eplebel** [comment]
while you're at it please add appropriate marginRight spacing to all leftIcons in buttons as per https://codesandbox.io/s/62z5q1j5wn 
` leftIcon: {
    marginRight: theme.spacing.unit,
  }`

**Comment by alexkyllo** [comment]
@onejgordon I left a comment on the commit, the use of the `pre_save` hook looks right, but I'm not sure lines 193-194 are needed (they look unreachable to me).

To accomplish "update the serialized object post validation (e.g. with stripped DOI url prefix) so that the UI updates with the real value" you will just need to instantiate and return a new ArticleSerializer with the saved article instance, just like I did here with `InvitationSerializer`: https://github.com/ScienceCommons/curate_science/blob/6af2ef9c4fb70d54003c98307b3f685a96cb3023/curate/views_api.py#L88

**Comment by onejgordon** [comment]
Thanks, I've updated the `update_article` API as follows:

https://github.com/ScienceCommons/curate_science/blob/staging/curate/views_api.py#L254-L261

**Comment by alexkyllo** [comment]
Cool, can you also add a test (or update an existing test), to verify that this DOI string handling works and is returned correctly to the client after an update?

**Comment by onejgordon** [comment]
Thanks for the reminder! Will do.

**Comment by eplebel** [comment]
DOI sanitization doesn't seem to work on staging (inputting "https://doi.org/10.1177/2515245918787489" still displays "https://doi.org/10.1177/2515245918787489" in the article list and being saved (instead of "10.1177/2515245918787489")

**Comment by alexkyllo** [comment]
The code only looks for `DOI_PREFIX = "https://dx.doi.org/"` so it wouldn't strip off "https://doi.org/" as written. It probably should use a regexp to match multiple variations of this domain. Something like this: `http[s]?:\/\/[^.]*[.]?doi.org\/`

**Comment by eplebel** [comment]
ah oops sorry i didn't realize that. yes we should add "https://doi.org/" and "http" variations (and possibly others when we encounter them).

**Comment by onejgordon** [comment]
Cool, I've updated to use a regex in https://github.com/ScienceCommons/curate_science/commit/844f3e0a0b2756e305e64dc5ec7c48fe197e7e39

**Comment by onejgordon** [comment]
On horizontal centering, I'm less familiar with this kind of layout, and it doesn't seem that it's natively supported by the material-ui library. 

We can of course establish a fixed width (similar to what we did for the centered article card column), but this makes flexible responsiveness more difficult (e.g. to naturally adapt to a mobile screen width). 

I'm seeing that Facebook uses this centered column approach, though many apps (e.g. Github) do not. Do sites like this one look similarly bad on high-res displays?

Anyway, there are certainly ways we can get content in the app bar centered and aligned to a fixed width, but wanted to run this by you before spending too much time getting material-ui's standard layouts to play nicely with some CSS hacks on both web and mobile.

**Comment by eplebel** [comment]
yes just like Facebook (and most other websites), please horizontally-center main container with max-width of 1100px  
(as a side note, the article card column should also be max-width rather than fixed width , like i had in my [alpha article list spec](https://etiennelebel.com/author/etienne.lebel.html), but this can be fixed later)

**Comment by eplebel** [comment]
re: DOI sanitizer, just discovered that trying to save a non-unique non-sanitized DOI does *not* correctly return the appropriate non-unique DOI error message. 

Steps:
1. create a new article on staging with following DOI "https://doi.org/10.1177/2515245918787489"
2. click Save. nothing happens

delete the prefix "https://doi.org/"
click Save
notice that now it correctly surfaces "article with this doi already exists."

**Comment by eplebel** [comment]
i'm really loving the new tooltips (awesome!), but can you display all of them *above* the target  , rather than below (like in the specs)? thanks!

**Comment by onejgordon** [comment]
@alexkyllo on the doi issue Etienne raised, I believe this is due to the fact that django does the uniqueness check (for props with unique=True) during `serializer.is_valid()`, and therefore prior to the handling of the pre_save signal where the doi may be changed. Is there a cleaner way to fix this than to do our doi sanitization 'manually' in a function call prior to `is_valid` in the API?

**Comment by onejgordon** [comment]
> yes just like Facebook (and most other websites), please horizontally-center main container with max-width of 1100px (as a side note, the article card column should also be max-width rather than fixed width , like i had in my alpha article list spec, but this can be fixed later)

@eplebel, on your author page alpha I see a max-width of 640px. Which ones is the 1100px you're referencing?

<img width="1281" alt="Screen Shot 2019-05-19 at 12 08 59 PM" src="https://user-images.githubusercontent.com/57584/57986874-2a1b6200-7a2f-11e9-8145-601fa76c5e4b.png">

**Comment by eplebel** [comment]
max-width of 1100px is for the entire container, which is based on logic from a [previous comment](https://github.com/ScienceCommons/curate_science/issues/36#issuecomment-476523117) as referenced above, but 1100px instead of 1000px so that the "In press" checkbox remains on the correct row.
![Untitled22](https://user-images.githubusercontent.com/4512335/57987865-7c6f7980-7a55-11e9-93c6-ae9af795b75d.png)

(please ignore the article card column max-width issue for now)

**Comment by alexkyllo** [comment]
> @alexkyllo on the doi issue Etienne raised, I believe this is due to the fact that django does the uniqueness check (for props with unique=True) during `serializer.is_valid()`, and therefore prior to the handling of the pre_save signal where the doi may be changed. Is there a cleaner way to fix this than to do our doi sanitization 'manually' in a function call prior to `is_valid` in the API?

@onejgordon I don't see how that can be the case--something else must be  going on. The uniqueness check is done in the database, after `pre_save` runs--when the update query is executed, PostgreSQL throws a SQL exception and psycopg2 catches it and throws a Python exception. I just tested this:

````python
>>> article1 = Article.objects.create(doi="https://doi.org/10.1177/2515245918787489", title="foo", year=2000)
>>> article1.doi
'10.1177/2515245918787489'
>>> article2 = Article.objects.create(doi="https://doi.org/10.1177/2515245918787489", title="foo", year=2001)
Traceback (most recent call last):
  File "/home/alex/.virtualenvs/curate_science/lib/python3.7/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
psycopg2.IntegrityError: duplicate key value violates unique constraint "curate_article_doi_fa06bbbf_uniq"
DETAIL:  Key (doi)=(10.1177/2515245918787489) already exists.
````

Etienne mentioned "nothing happens" when he clicks Save with the duplicate DOI, could it be that this exception is being thrown and is uncaught, resulting in a 500 from the API or something?

**Comment by alexkyllo** [comment]
> Etienne mentioned "nothing happens" when he clicks Save with the duplicate DOI, could it be that this exception is being thrown and is uncaught, resulting in a 500 from the API or something?

Upon local testing, that appears to be exactly what's happening. So I can think of two options: either do the `validate_doi` step, then a uniqueness check, in a [custom field validator](https://www.django-rest-framework.org/api-guide/serializers/#field-level-validation) on the `doi` field in the `ArticleSerializerNested`, or wrap `serializer.save()` in a try/catch block, catch the `psycopg2.IntegrityError` and return a nice error message to the client when the cleaned doi isn't unique.

https://github.com/ScienceCommons/curate_science/blob/6af2ef9c4fb70d54003c98307b3f685a96cb3023/curate/views_api.py#L231

**Comment by onejgordon** [comment]
Got it. I've implemented option 1. Can you confirm the pre_save signal is no longer needed with this serializer-level validation? Tests appear to be passing.

**Comment by onejgordon** [comment]
@eplebel I've pushed some updates to the dialog and topbar to constrain them to a centered 1100px column. Should the footer be centered and constrained as well?

**Comment by eplebel** [comment]
thanks. 

>>>> Should the footer be centered and constrained as well?
yes

please have the navbar the full width, but center the content within it like so:
![Untitled](https://user-images.githubusercontent.com/4512335/58101250-41805980-7bad-11e9-8bba-d30324479517.png)

also please increase the width of the edit article dialog (e.g. to 1175px) so that the "In press" checkbox remains on the correct row.

**Comment by eplebel** [comment]
> Got it. I've implemented option 1. Can you confirm the pre_save signal is no longer needed with this serializer-level validation? Tests appear to be passing.

DOI sanitization for non-unique non-sanitized DOIs now seems to be working, **BUT** the changes have broken the ability to (1) add new articles and (2) edit existing articles. :-(

Steps (new article bug):
1. click Add Article, enter title and author text and click Save

Notice nothing happens

Steps (edit article bug):
1. Edit an existing article
2. change title text and click Save

Notice the incorrect "DOI must be unique" error message

(as a side note, i'm admittedly very confused and concerned regarding how minor code changes for DOI sanitization would break the two core features of the current app....)

**Comment by onejgordon** [comment]
I've seen the issue, which seems to be that the new strategy for DOI sanitization didn't allow an empty DOI. 

This does highlight the need to improve our tests to include a case where no DOI is saved. Working on this now. Fix coming shortly.

**Comment by alexkyllo** [comment]
@onejgordon Right, the `pre_save` signal shouldn't be necessary anymore.

And I guess since the doi column is unique and nullable, two articles can't both have `""` (empty string) as their DOI, it has to be null. So you were right about needing to replace `""` with `None`.

**Comment by eplebel** [comment]
can now create & save new articles, but still can't edit an existing article that has a DOI (still incorrectly yields "DOI must be unique" error message)

**Comment by onejgordon** [comment]
Alex, I suspect we need to change the validation code to raise an exception
only when an article with different id exists with matching doi.

**Comment by alexkyllo** [comment]
Ah yep, this test works for creates but not updates:
`if len(Article.objects.filter(doi=value)) > 0:`

We will need to add another clause to exclude the current article serializer's id, if it has one. I can't test it right now but I think it would look something like this:

`if len(Article.objects.filter(doi=value).exclude(id=self.initial_data.get('id'))) > 0:`

**Comment by onejgordon** [comment]
Great, a second test added, and API creates/updates appear to be working well now w.r.t. doi

**Comment by eplebel** [comment]
yup looks like article creation and updating  are now working w.r.t. doi sanitization, thanks for the prompt response on this.

**Comment by eplebel** [comment]
a few final requests:
- bullet points for list of commentaries popup are now missing (this is working in production)
![Untitled2](https://user-images.githubusercontent.com/4512335/58184233-b5d6fd80-7c7e-11e9-873b-e8360d2f6eb4.png)

- final aesthetic tweaks for article card: 
  - reduce article card (.MuiCardContent-root-338) padding to 12px (from 16px) (also remove unnecessary padding-bottom specific value)
  - reduce article title (.ArticleLI-title-327) padding-top to 0px (from 2px)
  - add margin-top: 2px to .ArticleFullTextLinks div
  - reduce more button (.MuiIconButton-root-54) padding from 12px to 6px
![Untitled](https://user-images.githubusercontent.com/4512335/58184118-7f00e780-7c7e-11e9-83e1-50829b5d1c92.png)

- convert "EDIT" author button and "LINK EXISTING ARTICLE" button to outlined-secondary buttons (like the article EDIT, UNLINK, and DELETE buttons

**Comment by eplebel** [comment]
great, looks really good except for a minor issue whereby the more icon button is not correctly centering (seemingly) under these conditions:
- no transparency badges, all 3 full-text links, and a non-multi-line article title ([eg1](https://curate-science-staging-2.appspot.com/app/author/lorne-campbell#10), [eg2](https://curate-science-staging-2.appspot.com/app/author/lorne-campbell#10.1177/2515245918787489))

if only 1 or 2 of these conditions are true, the centering issue seems fine.

**Comment by onejgordon** [comment]
@eplebel do you have a screenshot showing the centering issue noted above? I assume it appears to be horizontally off-center? To me, the two examples linked to look centered (more arrow appears at the same horizontal location as for other articles on the page).

**Comment by eplebel** [comment]
oops sorry i think i modified the examples after posting the comment, so the conditions i described were no longer being met. the examples should *now* show it, and i've included a screenshot below:
![Untitled](https://user-images.githubusercontent.com/4512335/58442360-a7427900-80b8-11e9-9b84-be50cc697883.png)

**Comment by onejgordon** [comment]
Oops, yes, realized that after my comment.

OK, I've adjusted the layout with relative/absolute positioning of the more icon so that it's not sensitive to the positions of elements above. This appears to be working in all the cases I've tested, as well as all articles on [Lorne's](https://curate-science-staging-2.appspot.com/app/author/lorne-campbell) page on staging as well.

**Comment by eplebel** [comment]
ok looks like it's working, and i've completed all core UI regression tests, so please merge into production branch!
(i'll close this issue and move remaining issues into a new issue).
